language: cpp
dist: trusty

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      # - boost1.68
      - doxygen
      - graphviz

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5

